# Generated by Django 3.0.6 on 2020-07-20 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200719_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 39, 978307)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 39, 979308)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 39, 978307)),
        ),
    ]
