# Generated by Django 3.0.6 on 2020-07-20 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200720_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 43, 531492)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 43, 531492)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 14, 16, 43, 530492)),
        ),
    ]
