# Generated by Django 3.0.6 on 2020-07-20 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200720_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 0, 31, 984806)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 0, 31, 984806)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc_long',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 20, 15, 0, 31, 984806)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
