# Generated by Django 3.0.6 on 2020-07-25 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200722_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='listing',
            name='timestamp_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='timestamp_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 31, 28, 779148)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 31, 28, 779148)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 31, 28, 779148)),
        ),
    ]
