# Generated by Django 3.0.6 on 2020-07-25 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200724_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 35, 45, 480579)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 35, 45, 480579)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 35, 45, 480579)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
