# Generated by Django 3.0.6 on 2020-07-25 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200724_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 37, 16, 172637)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 37, 16, 173634)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 17, 37, 16, 170643)),
        ),
    ]
